apiVersion: v1
kind: Pod
metadata:
  name: pivotdude/social-network-web3-backend
  labels:
    pivotdude/social-network-web3-backend: latest
spec:
  containers:
    - name: social-network-web
      image: pivotdude/social-network-web3-backend:latest
      ports:
        - containerPort: 80
          name: http

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    pivotdude/social-network-web3-backend: latest
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 30000
  type: NodePort