name: Test build
on:
  pull_request:
    branches:
      - main

jobs:
  test_build:
    name: Docker build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build web
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: apps/web/Dockerfile
          tags: user/app:latest
