name: Test build
on:
  push:
    branches:
      - main
env:
  DOCKER_USERNAME: pivotdude
  BACKEND_TITLE: social-network-web3-frontend
  WEB_TITLE: social-network-web3-backend

jobs:
  test_build:
    name: Docker build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4
      - name: Build web
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./apps/web
          push: true
          tags: $DOCKER_USERNAME/$WEB_TITLE:latest
